version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app
      - media_files:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DATABASE_URL=sqlite:///db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  media_files: 