# Generated by Django 5.0 on 2024-12-26 16:44

import django.core.validators
import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='File name')),
                ('file', models.FileField(upload_to=files.models.get_file_path)),
                ('mime_type', models.CharField(max_length=127)),
                ('size', models.BigIntegerField(help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('encryption_key', models.BinaryField(help_text='Encrypted file key')),
                ('encryption_iv', models.BinaryField(help_text='Initialization vector used for encryption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'encrypted file',
                'verbose_name_plural': 'encrypted files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this link will expire', null=True)),
                ('password', models.CharField(blank=True, help_text='Optional password protection', max_length=128, null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this link has been accessed')),
                ('max_access_count', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this link can be accessed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareable_links', to='files.encryptedfile')),
            ],
            options={
                'verbose_name': 'shareable link',
                'verbose_name_plural': 'shareable links',
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_write', models.BooleanField(default=False, help_text='Whether the user can modify the file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.encryptedfile')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'file share',
                'verbose_name_plural': 'file shares',
                'unique_together': {('file', 'shared_with')},
            },
        ),
    ]
